### ISSUE TITLE
cant find dongletools.exe

### ISSUE THREAD

**Issue by Cloudrei** [AerialX/djmax-dongletools#1]
not sure where dongletools.exe is on this file, I haven't been able to locate it elsewhere.

**Comment by AerialX** [comment]
Hm, github must've deleted the old files from [whatever they had before releases were a thing](https://blog.github.com/2012-12-12-goodbye-uploads/)? I'll see about rebuilding it...

**Comment by AerialX** [comment]
Built and uploaded new binaries which are now linked from the README. I tried quickly testing with Windows 10 under QEMU but it didn't seem to work - hopefully that's just my system not having the drivers installed?

**Comment by enkidude101** [comment]
I have somewhat the same problem, but for me it states open dongle failed with error code a8160002.
